import AOSProvider from "@/components/AOSProvider";
import "./globals.css";

export const metadata = {
  title: "OAM Navigator",
  description: "Generated by create next app",
  icons: {
    icon: [
      { rel: "icon", url: "/favicon.ico" },
      { rel: "apple-touch-icon", url: "/apple-touch-icon.png", sizes: "180x180" },
    ],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <head>
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className="antialiased">
        <AOSProvider />
        {children}
      </body>
    </html>
  );
}
